resolver: nightly-2018-11-15

extra-deps:
- array-0.5.2.0
- process-1.6.4.0
- QuickCheck-2.12.6.1
- threepenny-gui-0.8.3.0
- time-units-1.0.0
# threepenny-gui
- io-streams-haproxy-1.0.0.2
- snap-core-1.0.3.2
- snap-server-1.1.0.0
- websockets-snap-0.10.3.0
packages:
- ouroboros-bm
- .
# - typed-transitions
